name: Black Duck scan
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build frontend
        run: |
          cd frontend && npm install
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.1
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'